apiVersion: v1
kind: Service
metadata:
  name: operations-performance
  namespace: operations-ai
spec:
  selector:
    app: operations-performance
  ports:
    - {name: http, port: 80, targetPort: http}
    - {name: metrics, port: 8000, targetPort: metrics}
  type: LoadBalancer

